fancybox: false ## If you want to use fancybox please set the value to true
duoshuo: ## Your duoshuo_shortname, e.g. haomwei
disqus: hohotechhk ## Your disqus_shortname, e.g. haomwei
google_search: true ## Use Google search, true/false
baidu_search: ## Use Baidu search, true/false
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
google_analytics: UA-54931547-4 ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000

menu:
  - page: home
    directory: .
    icon: icon-home
  - page: archive
    directory: archives/
    icon: icon-archive
  - page: about
    directory: about/
    icon: icon-about

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  # - category
  - tag
  - recent_posts
  # - recent_comments
  - links

links:
  - title: 好好科技 hohotech.hk
    url: http://hohotech.hk
